server:
  port: 9001
  error:
    path: /error

#backend:
#  host: us.umiuni.com  # Backend host
#  port: 5003         # Backend port
#  error:
#    path: /error

spring:
  datasource:
    url: jdbc:mysql://us.umiuni.com:3306/umi_shop
    username: root
    password: Voidmain4Voidmain4@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      platform: mysql

springfox:
  documentation:
    swagger:
      ui:
        base-url: /v2/api-docs

springdoc:
  api-docs:
    path: /v2/api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: mappings

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
#      springframework:
#        security: DEBUG

stripe:
  secret:
    key: sk_test_HNULuXYU2Y2e6HFczm6E5Nd6

paypal:
  client:
    id: ASWE1Q8AfwFxHoTDbB8tanMwQB8qRxb0i72hdPMD23RGzhNqY2DQoClXqQv8ONJWGPi_cy5ro5y_6tHB
    secret: EAxzPdtbxhyDw3mmSCRvcputnBrx5Ko_7a73fhfXNP5IRCDYoFExYJS5Qi--OhBTdEv0h0Cat7T_IZXj
  mode: 'sandbox'
