server:
  port: 9001
  error:
    path: /error

#backend:
#  host: https://v2.quickmall24.com/  # Backend host
#  port: 80         # Backend port
#  error:
#    path: /error

spring:
  datasource:
    url: jdbc:mysql://us.umiuni.com:3306/umi_shop
    username: root
    password: Voidmain4Voidmain4@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      platform: mysql
  rabbitmq:
    host: ec2-54-234-75-153.compute-1.amazonaws.com #127.0.0.1 #ec2-54-234-75-153.compute-1.amazonaws.com #127.0.0.1
    port: 5672
    username: guest
    password: guest

springfox:
  documentation:
    swagger:
      ui:
        base-url: /api-docs

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: mappings

stripe:
  secret:
    key: sk_test_HNULuXYU2Y2e6HFczm6E5Nd6

prod-backend: https://v2.quickmall24.com
prod-frontend: https://www.quickmall24.com
local-backend: http://localhost:9001
local-auth-backend: https://4811-66-253-183-231.ngrok-free.app
local-frontend: http://localhost:3000

paypal:
  client:
    id: AWhLD4_pmHlrCpHJSSKobJ4nwbwy_e16mcgbtrL_M5DzBaJk9zj84QYazMoy5TB7htSmjry7_ArOE9yU
    secret: EGVLVd0YufvNfz8ID2uN_mGRubofoTt2oZNy7CaYLGx2vHPCryZ5PuIve7LpLXxKQ7tDClvFePHBS7lN
  mode: 'sandbox'
  redirect:
    uri: ${prod-backend}/api/v1/suppliers/v2/callback
    test: ${local-auth-backend}/api/v1/suppliers/v2/callback
  frontend:
    base:
      uri: ${prod-frontend}
      test: ${local-frontend}
    redirect:
      uri: ${prod-frontend}/supplier-ims/
      test: ${local-frontend}/supplier-ims/
  referral:
    uri: ${prod-backend}/api/v1/suppliers/refer
    test: ${local-backend}/api/v1/suppliers/refer

#    id: ASWE1Q8AfwFxHoTDbB8tanMwQB8qRxb0i72hdPMD23RGzhNqY2DQoClXqQv8ONJWGPi_cy5ro5y_6tHB
#    secret: EAxzPdtbxhyDw3mmSCRvcputnBrx5Ko_7a73fhfXNP5IRCDYoFExYJS5Qi--OhBTdEv0h0Cat7T_IZXj

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
#      springframework:
#        security: DEBUG


# Define the names of your RabbitMQ queues
inventory:
  queue:
    name: inventory_queue
  lock:
    queue:
      name: inventory_lock_queue
  reduce:
    queue:
      name: inventory_reduction_queue

