package com.UmiUni.shop.service;

import com.UmiUni.shop.constant.ReportType;
import com.UmiUni.shop.entity.SupplierFinance;
import com.UmiUni.shop.model.FinancialReport;

import java.time.LocalDateTime;
import java.util.List;

public interface SuppliersFinanceService {
    FinancialReport generateDailyFinancialReport(Long valueOf, LocalDateTime startDateTime, LocalDateTime endDateTime, ReportType reportType);

    FinancialReport generateMonthlyFinancialReport(Long supplierId, LocalDateTime startDateTime, LocalDateTime endDateTime, ReportType reportType);

    FinancialReport generateYearlyFinancialReport(Long valueOf, LocalDateTime startDateTime, LocalDateTime endDateTime, ReportType reportType);

    List<SupplierFinance> getMonthlySalesReport(Long supplierId, String startDate, String endDate, ReportType reportType);

    List<SupplierFinance> getYearlySalesReport(Long supplierId, String start, String end, ReportType reportType);

    FinancialReport autoGenerateDailyFinancialReport(Long supplierId, LocalDateTime startDateTime, LocalDateTime endDateTime);

}
